// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1W9ikhQy2u36DjkFLk3dtFD5NSrhD5b4',
    appId: '1:503445488386:web:b0f5712bf43c98e7ef781b',
    messagingSenderId: '503445488386',
    projectId: 'contacts-4870f',
    authDomain: 'contacts-4870f.firebaseapp.com',
    storageBucket: 'contacts-4870f.appspot.com',
    measurementId: 'G-6WPS6YT6X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWTEdGpidrojiTaV4zQ6t5dgaYS7jCjWk',
    appId: '1:503445488386:android:10e79df13cca9461ef781b',
    messagingSenderId: '503445488386',
    projectId: 'contacts-4870f',
    storageBucket: 'contacts-4870f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNPucm_li6jGGC5YIp8AzH4-GkHWnG_bc',
    appId: '1:503445488386:ios:53ac6b37ba4a6d2def781b',
    messagingSenderId: '503445488386',
    projectId: 'contacts-4870f',
    storageBucket: 'contacts-4870f.appspot.com',
    iosClientId: '503445488386-7iqrndmdbrnh25shrmufkpl2apouk2hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.contacts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNPucm_li6jGGC5YIp8AzH4-GkHWnG_bc',
    appId: '1:503445488386:ios:53ac6b37ba4a6d2def781b',
    messagingSenderId: '503445488386',
    projectId: 'contacts-4870f',
    storageBucket: 'contacts-4870f.appspot.com',
    iosClientId: '503445488386-7iqrndmdbrnh25shrmufkpl2apouk2hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.contacts',
  );
}
